name: Deploy Server Application
on:
  push:
    branches:
      - main

jobs:
  build:
  runs-on:ubuntu-latest
  steps:
    - name: Checkout Source code
      uses: action/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t vedang10/server .
    - name: Publish image to Docker hub
      run: docker push vedang10/server:latest
  
  deploy:
    needs: build
      runs-on: self-hosted
      steps:
        - name: Pull image from docker hub
          run: docker pull vedang10/server:latest
        - name: Run Docker Container
          run: docker run -d -p 5000:5000 --name server-app-container -e DATABASE_URL='${{secrets.MONGO_URL}}' -e SECRET={{secrets.SECRET}} -e EMAIL_HOST={{secrets.EMAIL_HOST}}  -e EMAIL_PORT={{secrets.EMAIL_PORT}}  -e EMAIL_HOST_USER={{secrets.EMAIL_HOST_USER}} -e EMAIL_HOST_PASSWORD={{secrets.EMAIL_HOST_PASSWORD}} vedang10/server