name: Deploy Client Application
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t vedang10/client --build-arg REACT_APP_SERVER_URL='${{ secrets.REACT_APP_SERVER_URL }}' ./client
      - name: Publish image to Docker Hub
        run: docker push vedang10/client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Docker Installation
        run: docker --version
      - name: Pull image from Docker Hub
        run: docker pull vedang10/client:latest
      - name: Delete old container if exists
        run: |
          if [ $(docker ps -q -f name=client-app-container) ]; then
            docker rm -f client-app-container
          fi
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name client-app-container vedang10/client
