name: Deploy Server Application
on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t vedang10/server ./server
      - name: Publish image to Docker Hub
        run: docker push vedang10/server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull vedang10/server:latest
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name server-app-container \
            -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            -e SECRET='${{ secrets.SECRET }}' \
            -e EMAIL_HOST='${{ secrets.EMAIL_HOST }}' \
            -e EMAIL_PORT='${{ secrets.EMAIL_PORT }}' \
            -e EMAIL_HOST_USER='${{ secrets.EMAIL_HOST_USER }}' \
            -e EMAIL_HOST_PASSWORD='${{ secrets.EMAIL_HOST_PASSWORD }}' \
            vedang10/server
