name: Deploy Client Application
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t vedang10/client --build-arg REACT_APP_SERVER_URL='${{ secrets.REACT_APP_SERVER_URL }}' ./client
      - name: Publish image to Docker Hub
        run: docker push vedang10/client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull vedang10/client:latest
      - name: Delete old container
        run: docker rm -f client-app-container
      - name: Run Docker Container
        run: docker run -d -p 3001:80 --name client-app-container vedang10/client
